system( "cp -f ~/.bash_profile ~/work/dotfiles/.bash_profile" )
system( "cp -f ~/.gemrc ~/work/dotfiles/.gemrc" )
system( "cp -f ~/.gitconfig ~/work/dotfiles/.gitconfig" )
system( "cp -f ~/.gitignore ~/work/dotfiles/.gitignore" )
system( "cp -f ~/.railsrc ~/work/dotfiles/.railsrc" )
